name: Frontend Deploy
on:
  push:
    branches: ["main"]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: oceanguard-frontend/package-lock.json
      - name: Install dependencies (frontend)
        working-directory: oceanguard-frontend
        run: npm ci || npm i
      - name: Build and export static site
        working-directory: oceanguard-frontend
        env:
          GITHUB_PAGES: "true"
        run: |
          npm run build
          npm run export
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: oceanguard-frontend/dist
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
